spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/file-db
    username: postgres
    password: ruhan
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB